### ISSUE TITLE
Potential bug while parsing comments

### ISSUE THREAD

**Issue by lefessan** [tonlabs/ever-assembler#28]
Hi,

  We are reviewing the code of this module, and found a potential vulnerability. Could you confirm if it is a bug / unwanted behavior ?

Here is the potential problem we spotted:
https://github.com/tonlabs/ton-labs-assembler/blob/c1112f915464167c1005c885e576092a8eca6375/src/lib.rs#L299

Contrary to other tokens, the `continue` is not guarded by a `if s0 == s1 {`. As a consequence, the token just before the `;` is discarded. This might be unintentional, and lead to potential attacks.

For example:
```
PUSHINT 7; we push 7 on the stack
PUSHINT; we push 15 now
   15
DROP; we drop the 15 from the stack, keeping 7
```
Here, tokens `7`, `PUSHINT` and `DROP` are silently discarded (no space before `;`), so that actually, the stack contains `15` instead of `7`, contrary to what a reader might believe.

**Comment by mskvortsov** [comment]
Thank you for the finding. Yes, it is a bug. In a couple of days (hopefully), a fix will be auto-merged into this public repo from a private one.
